 spring:
   datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://139.129.220.209:3306/test
     username: mjmh
     password: mjmhtest2017
   jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
